name = "sp_tensor_cp"
uuid = "4fd100f9-7c1e-4866-9d34-a2472cd4508b"
authors = ["Huangpf <huangpf@hnu.edu.cn> and contributors "]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
TSSOS = "81648402-ffe6-11e9-2394-0de17a9afdad"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
DynamicPolynomials = "0.4.6"
HomotopyContinuation = "2.9.1"
JuMP = "1.25.0"
Mosek = "11.0.0"
MosekTools = "0.15.9"
MultivariateMoments = "0.3.10"
MultivariatePolynomials = "0.4.7"
RowEchelon = "0.2.1"
TSSOS = "1.3.4"
TypedPolynomials = "0.3.2"
